/**
 * Central export file for all types
 * FastRezu 2.0 (V2) - Backward compatible with V1 routes
 */

// V2: Main database type (auto-generated by Supabase)
export type { Database, Tables } from "./database.types";

// V2 Convenience aliases
import type { Tables as SupaTables } from "./database.types";
export type UserProfile = SupaTables<'user_profiles'>;
export type Profile = SupaTables<'profiles'>;

// V1 Table types - Kept for backward compatibility with existing API routes
export type {
  // User
  UserProfileInsert,
  UserProfileUpdate,
  // CV
  CV,
  CVInsert,
  CVUpdate,
  // CV Sections
  CVSection,
  CVSectionInsert,
  CVSectionUpdate,
  CVSectionType,
  // JD Analysis
  JDAnalysis,
  JDAnalysisInsert,
  JDAnalysisUpdate,
  // ATS Suggestions
  ATSuggestion,
  ATSuggestionInsert,
  ATSuggestionUpdate,
  // Feedback
  Feedback,
  FeedbackInsert,
  FeedbackUpdate,
  FeedbackType,
  FeedbackPriority,
  FeedbackStatus,
  // Feedback Attachments
  FeedbackAttachment,
  FeedbackAttachmentInsert,
  FeedbackAttachmentUpdate,
} from "./tables";
