/**
 * Central export file for all types
 * FastRezu 2.0 (V2)
 */

// Main database type (auto-generated by Supabase CLI)
export type { Database } from "./database.types";

// ==========================================
// V1 Types - Commented out for V2 Migration
// ==========================================

/*
export type {
  // User
  UserProfile,
  UserProfileInsert,
  UserProfileUpdate,
  // CV
  CV,
  CVInsert,
  CVUpdate,
  // CV Sections
  CVSection,
  CVSectionInsert,
  CVSectionUpdate,
  CVSectionType,
  // JD Analysis
  JDAnalysis,
  JDAnalysisInsert,
  JDAnalysisUpdate,
  // ATS Suggestions
  ATSuggestion,
  ATSuggestionInsert,
  ATSuggestionUpdate,
  // Feedback
  Feedback,
  FeedbackInsert,
  FeedbackUpdate,
  FeedbackType,
  FeedbackPriority,
  FeedbackStatus,
  // Feedback Attachments
  FeedbackAttachment,
  FeedbackAttachmentInsert,
  FeedbackAttachmentUpdate,
} from "./tables";
*/
